### ISSUE TITLE
`KeyError: 'currency->oil'` after setup

### ISSUE THREAD

**Issue by XBagon** [Apollys/PoEDynamicLootFilter#20]
I input the PoE filter directory and then the setup completed and the output included an error: 

```
Profile "Default" created!
Traceback (most recent call last):
  File "X:\Code\Clones\PoEDynamicLootFilter\backend_cli.py", line 1059, in <module>
    main()
  File "X:\Code\Clones\PoEDynamicLootFilter\backend_cli.py", line 1055, in main
    raise e
  File "X:\Code\Clones\PoEDynamicLootFilter\backend_cli.py", line 1050, in main
    main_impl()
  File "X:\Code\Clones\PoEDynamicLootFilter\backend_cli.py", line 1037, in main_impl
    DelegateFunctionCall(loot_filter, function_name, function_params)
  File "X:\Code\Clones\PoEDynamicLootFilter\backend_cli.py", line 447, in DelegateFunctionCall
    loot_filter.ApplyImportChanges()
  File "X:\Code\Clones\PoEDynamicLootFilter\loot_filter.py", line 1162, in ApplyImportChanges
    oil_hide_rule = self.type_tier_rule_map[consts.kOilTypeTag][consts.kOilHideTierTag]
KeyError: 'currency->oil'
Config data saved to "Profiles\Default.config".
You can edit this file at any time later to update these settings.

Setup complete! Enjoy PoE Dynamic Loot Filter!
Press Enter to close setup.py
```

I will try to use it like it is, but this probably shouldn't be happening so I though I'd just report it :)

**Comment by XBagon** [comment]
Turns out it also didn't put the `DynamicLootFilter.filter` into the PoE folder and the AHK script crashed directly.

**Comment by XBagon** [comment]
[wreckers_ssfffe.filter.txt](https://github.com/Apollys/PoEDynamicLootFilter/files/8931483/wreckers_ssfffe.filter.txt)

**Comment by Apollys** [comment]
This is not a FilterBlade filter, so DLF doesn't know how to parse it.

Please review the [Readme](https://github.com/Apollys/PoEDynamicLootFilter#dlf-requirements) or come to the [Discord](https://discord.gg/gH9MzgCzMJ)for more detailed setup instructions.

**Comment by XBagon** [comment]
oh I'm sorry, that makes a lot of sense. I completely missed that part. Sorry for wasting your time 😅.

**Comment by Apollys** [comment]
No worries! In the dev branch I've added simple check on import to see if the filter looks like a FilterBlade filter, and if not, display a clearer error message to the user. 😄
